language: python
sudo: false

python:
  - "3.3"
  - "3.4"
  - "3.5"

virtualenv:
  system_site_packages: false

services:
  - postgresql

install:
  - pip install psycopg2
  - pip install anyblok_pyramid
  - pip install flake8
  - pip install coverage
  - pip install nose
  - pip install WebTest
  - pip install coveralls
  - python setup.py develop

env:
  global:
    - ANYBLOK_DATABASE_NAME=travis_ci_test
    - ANYBLOK_DATABASE_DRIVER=postgresql
    - ANYBLOK_DATABASE_USER=postgres

script:
  - flake8 anyblok_pyramid_beaker
  - psql -c 'create database travis_ci_test;' -U postgres
  - nosetests anyblok_pyramid_beaker/tests -v -s --with-coverage --cover-package=anyblok_pyramid_beaker
  
after_success:
  coveralls
