language: python
dist: xenial
sudo: false

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: "3.7-dev"
    - python: "3.8-dev"
    - python: "nightly"

virtualenv:
  system_site_packages: false

services:
  - postgresql

install:
  - pip install -U pip
  - pip install wheel
  - pip install -U flake8 pytest pytest-cov
  - pip install psycopg2
  - pip install WebTest
  - pip install coveralls
  - pip install .

env:
  global:
    - ANYBLOK_DATABASE_NAME=travis_ci_test
    - ANYBLOK_DATABASE_DRIVER=postgresql
    - ANYBLOK_DATABASE_USER=postgres

script:
  - flake8 anyblok_pyramid_beaker
  - psql -c 'create database travis_ci_test;' -U postgres
  - pytest --cov-report= --cov=anyblok_pyramid_beaker anyblok_pyramid_beaker/bloks
  
after_success:
  coveralls --data_file=.coverage --config_file=.coveragerc
